---
- name: Deploy ecommerce app
  hosts: n1
  become: yes

  tasks:
  - name: Install git
    apt:
      name: git
      state: present

  - name: Host Code
    git:
      repo: https://github.com/CeeyIT-Solutions/ecomm-3.git
      dest: /var/www/html/
      force: yes
...